### ISSUE TITLE
Bug: Right Click Menu showing for multiple characters with the same name but different world

### ISSUE THREAD

**Issue by AetherCollective** [Blooym/Wholist#52]
Bug occurs when right clicking on one of multiple users with the same first and last names but from a different worlds.

Expected Behaviour: Clicking on a user will open a right click menu ONLY FOR THEM.

![image](https://github.com/user-attachments/assets/6cfe245b-30f1-457a-8749-f314bdd06053)

**Comment by Blooym** [comment]
Can get this easily fixed when back from vacation.

**Comment by Blooym** [comment]
Should now be resolved, let me know if you run into this again

**Comment by AetherCollective** [comment]
I just saw them again, unfortunately it is still broken and not working.

**Comment by Blooym** [comment]
New version hasn't been distributed to Dalamud quite yet as I haven't had time, hopefully I can do soon

**Comment by AetherCollective** [comment]
![image](https://github.com/user-attachments/assets/7bb8322c-89be-419f-bae9-2a5c8c2fc436)

**Comment by AetherCollective** [comment]
Confirmed fixed now. Thanks!
